services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'jonas'
      MONGO_INITDB_ROOT_PASSWORD: '123456789'
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
